"""add_vidas_moedas_congelamento_e_atividades_diarias

As colunas novas (vidas, moedas, congelamentos_disponiveis) usam
server_default pra que linhas ja existentes na tabela sejam preenchidas com
um valor real em vez de NULL -- sem isso, `estudante.vidas >= VIDAS_MAXIMAS`
quebraria com TypeError pra qualquer estudante cadastrado antes desta
migracao (o default=5 do SQLAlchemy so se aplica em INSERT novo, nao em
ALTER TABLE de linha existente).

Revision ID: 0bef1f384ef7
Revises: 5a066f7fb058
Create Date: 2026-08-20 02:45:45.349824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bef1f384ef7'
down_revision: Union[str, Sequence[str], None] = '5a066f7fb058'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atividades_diarias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estudante_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.ForeignKeyConstraint(['estudante_id'], ['estudantes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('estudante_id', 'data', name='uq_atividade_estudante_data')
    )
    op.create_index(op.f('ix_atividades_diarias_id'), 'atividades_diarias', ['id'], unique=False)
    op.add_column('estudantes', sa.Column('vidas', sa.Integer(), nullable=True, server_default='5'))
    op.add_column('estudantes', sa.Column('proxima_vida_em', sa.DateTime(), nullable=True))
    op.add_column('estudantes', sa.Column('moedas', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('estudantes', sa.Column('congelamentos_disponiveis', sa.Integer(), nullable=True, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('estudantes', 'congelamentos_disponiveis')
    op.drop_column('estudantes', 'moedas')
    op.drop_column('estudantes', 'proxima_vida_em')
    op.drop_column('estudantes', 'vidas')
    op.drop_index(op.f('ix_atividades_diarias_id'), table_name='atividades_diarias')
    op.drop_table('atividades_diarias')
    # ### end Alembic commands ###
