"""add_itinerario_to_estudantes

Revision ID: 5a066f7fb058
Revises: 6aa7c8effe06
Create Date: 2026-08-20 01:17:01.488122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a066f7fb058'
down_revision: Union[str, Sequence[str], None] = '6aa7c8effe06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estudantes', sa.Column('itinerario', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('estudantes', 'itinerario')
    # ### end Alembic commands ###
