"""add_quizzes_perfeitos_seguidos

Revision ID: 64efd66e9fbb
Revises: 0bef1f384ef7
Create Date: 2026-08-20 03:05:05.462190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64efd66e9fbb'
down_revision: Union[str, Sequence[str], None] = '0bef1f384ef7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estudantes', sa.Column('quizzes_perfeitos_seguidos', sa.Integer(), nullable=True, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('estudantes', 'quizzes_perfeitos_seguidos')
    # ### end Alembic commands ###
