"""nome_de_login_deixa_de_ser_unico

Revision ID: 71ed679e4129
Revises: d1f54873be22
Create Date: 2026-08-20 04:06:23.861253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71ed679e4129'
down_revision: Union[str, Sequence[str], None] = 'd1f54873be22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_estudantes_nome'), table_name='estudantes')
    op.create_index(op.f('ix_estudantes_nome'), 'estudantes', ['nome'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_estudantes_nome'), table_name='estudantes')
    op.create_index(op.f('ix_estudantes_nome'), 'estudantes', ['nome'], unique=True)
    # ### end Alembic commands ###
