"""adiciona quiz_sessoes e pergunta de seguranca

Revision ID: 80ab636f391b
Revises: 71ed679e4129
Create Date: 2026-08-20 04:38:12.700804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80ab636f391b'
down_revision: Union[str, Sequence[str], None] = '71ed679e4129'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_sessoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estudante_id', sa.Integer(), nullable=False),
    sa.Column('tema', sa.String(length=120), nullable=False),
    sa.Column('gabarito', sa.JSON(), nullable=False),
    sa.Column('respostas', sa.JSON(), nullable=False),
    sa.Column('dicas_usadas', sa.Integer(), nullable=False),
    sa.Column('concluido', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['estudante_id'], ['estudantes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_sessoes_id'), 'quiz_sessoes', ['id'], unique=False)
    op.add_column('estudantes', sa.Column('pergunta_seguranca', sa.String(length=200), nullable=True))
    op.add_column('estudantes', sa.Column('resposta_seguranca_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('estudantes', 'resposta_seguranca_hash')
    op.drop_column('estudantes', 'pergunta_seguranca')
    op.drop_index(op.f('ix_quiz_sessoes_id'), table_name='quiz_sessoes')
    op.drop_table('quiz_sessoes')
    # ### end Alembic commands ###
