"""add_linkedin_e_reset_de_senha

Revision ID: d1f54873be22
Revises: eee8ec2ea442
Create Date: 2026-08-20 03:59:43.983345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1f54873be22'
down_revision: Union[str, Sequence[str], None] = 'eee8ec2ea442'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estudantes', sa.Column('linkedin', sa.String(length=255), nullable=True))
    op.add_column('estudantes', sa.Column('precisa_trocar_senha', sa.Boolean(), nullable=True, server_default=sa.false()))
    op.create_index(op.f('ix_estudantes_nome'), 'estudantes', ['nome'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_estudantes_nome'), table_name='estudantes')
    op.drop_column('estudantes', 'precisa_trocar_senha')
    op.drop_column('estudantes', 'linkedin')
    # ### end Alembic commands ###
