"""add_auth_e_candidaturas

Revision ID: eee8ec2ea442
Revises: 64efd66e9fbb
Create Date: 2026-08-20 03:44:58.067340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eee8ec2ea442'
down_revision: Union[str, Sequence[str], None] = '64efd66e9fbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidaturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estudante_id', sa.Integer(), nullable=False),
    sa.Column('vaga_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('criada_em', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['estudante_id'], ['estudantes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vaga_id'], ['vagas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('estudante_id', 'vaga_id', name='uq_candidatura_estudante_vaga')
    )
    op.create_index(op.f('ix_candidaturas_id'), 'candidaturas', ['id'], unique=False)
    op.add_column('estudantes', sa.Column('senha_hash', sa.String(length=255), nullable=True))
    op.add_column('vagas', sa.Column('area_itinerario', sa.String(length=60), nullable=True))
    op.add_column('vagas', sa.Column('descricao_completa', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vagas', 'descricao_completa')
    op.drop_column('vagas', 'area_itinerario')
    op.drop_column('estudantes', 'senha_hash')
    op.drop_index(op.f('ix_candidaturas_id'), table_name='candidaturas')
    op.drop_table('candidaturas')
    # ### end Alembic commands ###
